### ISSUE TITLE
Millisecond timestamp resolution missing

### ISSUE THREAD

**Issue by robertvanv** [dyster/IPTComShark#8]
As of the latest version 1.5.0.0, the timestamp no longer shows millisecond resolution. This is very useful when determining communications breakdown between CCU-O, EVC, DMI etc.

Please re-include the millisecond display within the timestamp of packets.

**Comment by dyster** [comment]
The ms display has been separated into a separate column to the right of the timestamp.
This was due to the terrible sorting performance of the timestamp column, as the built in ColumnComparer that comes with the listview does string comparison instead of int comparison when the time has been formatted.
Does it need to be in the same column? I can fix it eventually but I need to figure how to put a custom sorter on it to ignore the formatting step.

**Comment by robertvanv** [comment]
I think the separate column is actually better. It makes it easier to find the time initially, and then narrow down the search if need be.
